language: python

matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38

before_install:
  - mkdir -p vendor/protoc && pushd vendor/protoc
    && curl -LO 'https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip'
    && unzip protoc-3.4.0-linux-x86_64.zip
    && popd
  - export PATH=$PWD/vendor/protoc/bin:$PATH

install:
  - pip install tox

script:
  - tox --skip-missing-interpreters
